name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    env:
     
      PKR_VAR_image_publisher: ${{ variables.image_publisher }}
      PKR_VAR_image_offer: ${{ variables.image_offer }}
      PKR_VAR_image_sku: ${{ variables.image_sku }}
      PKR_VAR_location: ${{ variables.location }}
      PKR_VAR_vm_size: ${{ variables.vm_size }}
      PKR_VAR_winrm_timeout: ${{ variables.winrm_timeout }}
      PKR_VAR_resource_group: ${{ variables.resource_group }}
      PKR_VAR_gallery_name: ${{ variables.gallery_name }}
      PKR_VAR_image_name: ${{ variables.image_name }}
      PKR_VAR_image_version: ${{ variables.image_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install -y packer

    - name: Configure Azure credentials
      run: |
        export AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPION_ID }}
        export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
        export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
        export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
        export AZURE_CLIENT_VALUE=${{ secrets.AZURE_CLIENT_VALUE }}

    - name: Initialize Packer
      run: packer init Development/windows_2019.pkr.hcl

    - name: Verify Packer Installation
      run: packer version

    - name: Validate Packer template
      run: packer validate Development/windows_2019.pkr.hcl

    - name: Build with Packer
      run: packer build Development/windows_2019.pkr.hcl
