name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: Validate Packer template
      run: packer validate Development/windows_2019.pkr.hcl
      
    - name: Build with Packer
      run: packer build Development/windows_2019.pkr.hcl
