name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Packer
      run: |
        if (-not (Get-Command "packer" -ErrorAction SilentlyContinue)) {
          Write-Host "Packer could not be found, installing..."
          choco install packer -y
        }
      
    - name: Validate Packer template
      run: packer validate Development/windows_2019.pkr.hcl
      
    - name: Build with Packer
      run: packer build Development/windows_2019.pkr.hcl
