name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Validate Packer template
      run: packer validate <your-template.json>
      
    - name: Build with Packer
      run: packer build <your-template.json>
