name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Packer
      run: |
        sudo apt-get install -y packer
      
    - name: Validate Packer template
      run: packer validate Development/windows_2019.pkr.hcl
      
    - name: Build with Packer
      run: packer build Development/windows_2019.pkr.hcl
