name: Packer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Validate Packer template
      run: packer validate windows_2019.pkr.hcl
      
    - name: Build with Packer
      run: packer build windows_2019.pkr.hcl
